version: '3.3'
services:

  db:
    image: postgres:13.10
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 2s
      retries: 2
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: puristaako/foodgram_backend:latest
    env_file: .env
    volumes:
      - static_foodgram:/backend_static
      - media_foodgram:/app/media
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: puristaako/foodgram_frontend:latest
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static_foodgram:/staticfiles/
  
  nginx:
    image: puristaako/foodgram_gateway:latest
    ports:
      - '9000:80'
    volumes:
      - static_foodgram:/staticfiles/
      - media_foodgram:/media/
    depends_on:
      - backend

volumes:
  pg_data:
  static_foodgram:
  media_foodgram: